import { mkdirSync, readFileSync } from 'node:fs';
import { chromium } from 'playwright';

const out = process.env.ORBIT_SCREENSHOTS || new URL('./screenshots/', import.meta.url).pathname;
const catalog = JSON.parse(readFileSync(new URL('../collection-catalog.json', import.meta.url)));
const expectedFamilies = Object.values(catalog.families).filter(family => family.variants.filter(item => item.status === 'success').length >= 2).length;
mkdirSync(out, { recursive: true });
let browser = await chromium.launch({ executablePath: '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox', '--enable-webgl', '--use-gl=angle', '--use-angle=swiftshader'] });
const errors = [];
let page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
const waitReady = async () => page.waitForFunction(() => document.querySelector('#status')?.textContent.includes('불러옴'), null, { timeout: 20000 });

await page.goto('http://127.0.0.1:8877/?model=baseball-geometry&background=stadium', { waitUntil: 'domcontentloaded' });
await page.waitForURL(url => url.pathname.endsWith('/lab.html') && (url.searchParams.get('variant') || url.searchParams.get('model')) === 'baseball-geometry');
await waitReady();
if (await page.locator('#familySelect option').count() !== expectedFamilies) throw new Error('lab should expose only multi-version families');
if (await page.locator('#familySelect').inputValue() !== 'baseball') throw new Error('legacy baseball deep link selected wrong family');
if (await page.locator('#variantSelect option').count() !== 5) throw new Error('baseball lab should show five versions');
await page.screenshot({ path: `${out}/lab-baseball-desktop.png`, fullPage: false });
await page.selectOption('#variantSelect', 'baseball-retexture');
await waitReady();
if (!page.url().includes('variant=baseball-retexture') || !page.url().includes('family=baseball') || !page.url().includes('background=stadium')) throw new Error('model/family/background query was not preserved');
await page.screenshot({ path: `${out}/lab-legacy-variant.png`, fullPage: false });
await page.goBack();
await page.waitForFunction(() => new URL(location.href).searchParams.get('variant') === 'baseball-geometry');
await waitReady();
await page.goForward();
await page.waitForFunction(() => new URL(location.href).searchParams.get('variant') === 'baseball-retexture');
await waitReady();
await page.locator('#backgroundChoices [data-background="auto"]').click();
await page.waitForFunction(() => document.querySelector('#backgroundStatus').textContent.includes('경기장'));
const historyBeforeFamilyChange = await page.evaluate(() => history.length);
await page.selectOption('#familySelect', 'pikachu');
await waitReady();
if (await page.locator('#variantSelect option').count() !== 2) throw new Error('pikachu family should expose two versions');
if (await page.evaluate(() => history.length) !== historyBeforeFamilyChange + 1) throw new Error('family change should create exactly one history entry');
if (!page.url().includes('family=pikachu') || !page.url().includes('variant=pikachu-sol')) throw new Error('family change did not load and synchronize its representative');
await page.waitForFunction(() => document.querySelector('#backgroundStatus').textContent.includes('햇살 초원'));
await page.screenshot({ path: `${out}/lab-pikachu-desktop.png`, fullPage: false });
await page.goBack();
await page.waitForFunction(() => new URL(location.href).searchParams.get('family') === 'baseball');
await waitReady();
if (await page.locator('#familySelect').inputValue() !== 'baseball') throw new Error('back navigation did not restore selected family');
await page.goForward();
await page.waitForFunction(() => new URL(location.href).searchParams.get('family') === 'pikachu');
await waitReady();
await page.setViewportSize({ width: 390, height: 844 });
await page.goto('http://127.0.0.1:8877/lab.html?family=pikachu&variant=pikachu-astra&background=meadow', { waitUntil: 'domcontentloaded' });
await waitReady();
if (!page.url().includes('variant=pikachu-astra')) throw new Error('family/variant URL was not retained on direct open');
await page.screenshot({ path: `${out}/lab-mobile.png`, fullPage: false });
if (errors.length) throw new Error(`browser console/page errors: ${errors.join(' | ')}`);
console.log(JSON.stringify({ screenshots: out, legacyRedirect: 'passed', labFamilies: 2, baseballVersions: 5, pikachuVersions: 2, automaticBackgroundAndFamilyChange: 'passed', browserHistory: 'passed', mobileFamilyVariant: 'passed', errors }, null, 2));
await browser.close();
